name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: bookreserve_db_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -u root -prootpassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, dom, filter, gd, json
        tools: composer:v2

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Setup test environment
      run: |
        cp .env .env.test.local
        echo 'DATABASE_URL="mysql://root:rootpassword@127.0.0.1:3306/bookreserve_db_test?serverVersion=8.0"' >> .env.test.local
        echo 'MESSENGER_TRANSPORT_DSN=doctrine://default' >> .env.test.local

    - name: Wait for MySQL
      run: |
        until mysqladmin ping -h 127.0.0.1 -P 3306 -u root -prootpassword --silent; do
          echo 'Waiting for MySQL...'
          sleep 2
        done
        echo "MySQL is ready!"

    - name: Verify MySQL connection
      run: |
        mysql -h 127.0.0.1 -P 3306 -u root -prootpassword -e "SHOW DATABASES;"

    - name: Create database schema
      run: |
        php bin/console doctrine:migrations:migrate --env=test --no-interaction

    - name: Run tests
      run: |
        php bin/phpunit --coverage-text